# 상권분석: 장어집 기준표 점수 · 생존율 · 3km 차량 상권 · 경쟁 아님 · 손익 · 심사 기록 (t62 의 가짜 SDK·중계를 빌려 씀)
import asyncio
src=open('tests/t62.py',encoding='utf-8').read().rsplit('asyncio.run(main())',1)[0]
G={'__name__':'t62'}; exec(src,G)
from playwright.async_api import async_playwright
async def main():
  FAILS=G['FAILS']; ok=G['ok']
  async with async_playwright() as p:
    b=await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
    pg=await (await b.new_context(viewport={'width':1300,'height':900})).new_page(); errs=[]
    pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('dialog',lambda d: asyncio.ensure_future(d.accept()))
    await pg.route('**/*',G['handler']); await pg.goto('http://localhost:8765/sangkwon.html'); await pg.wait_for_timeout(600)
    ok('0) 새 기계(저장소 비어 있음)에서도 기준 만들기 없이 바로 분석', '기준 만들기' not in await pg.inner_text('#pane'))
    await pg.fill('#q','대구 수성구 범어동 177'); await pg.click('[data-act=find]'); await pg.wait_for_timeout(300)
    await pg.click('[data-cand="0"]'); await pg.wait_for_function("document.querySelector('.scorebox')",timeout=60000); await pg.wait_for_timeout(300)
    body=await pg.inner_text('#pane')
    ok('1) 장어집 기준표 점수 (비교·순위 문구 없음)', '장어집 기준표' in body and '곳 중' not in await pg.inner_text('.mix') and '기준 상권' not in body)
    ok('2) 차량 상권(3km) 영역', '차량 상권 (3km)' in body)
    sc=await pg.evaluate("(()=>{const c=DB.cands[0]; const s=scoreOf(c.m,c); const g=k=>{for(const dm of s.dims) for(const x of dm.subs) if(x.k===k) return x.p; return null}; return [g('food500'),g('park500'),g('n500'),g('eel3k'),s.mkt!=null]})()")
    ok('3) 지표 점수가 기준표(AB)대로 계산', all(v is not None for v in sc[:4]) and sc[4], sc)
    bands=await pg.evaluate("[band(12,AB.park500),band(1000,AB.subD),band(2,AB.n500),band(0,AB.eel3k),band(5,AB.eel3k),band(40,AB.eel3k)]")
    ok('4) 기준표 값: 주차 12곳 80 · 지하철 1km 55 · 장어집 2곳 60 · 3km 장어 0곳 35/5곳 90/40곳 25', bands==[80,55,60,35,90,25], bands)
    sv=await pg.evaluate("(()=>{const c=DB.cands[0]; return [c.m.eelSurv3,c.m.eelSurvN,c.m.eelDongOn,c.m.eelDongClose5]})()")
    ok('5) 장어집 3년 생존율 80% (5곳 중 4곳) · 범어동 영업 3곳', sv==[80,5,3,0], sv)
    ok('   SWOT 에 생존율 기회 문장', '3년 생존율이 80%' in body)
    r0=await pg.evaluate("scoreOf(DB.cands[0].m,DB.cands[0]).d.n1k")
    await pg.check('[data-cx=e1]'); await pg.wait_for_timeout(300)
    r1=await pg.evaluate("scoreOf(DB.cands[0].m,DB.cands[0]).d.n1k"); ex=await pg.evaluate("DB.cands[0].compEx")
    ok('6) 경쟁 아님 체크 → 장어집 수에서 빠지고 저장', r1==r0-1 and ex=={'e1':1}, (r0,r1,ex))
    await pg.fill('[data-f=rent]','300'); await pg.fill('[data-f=area]','40'); await pg.wait_for_timeout(500)
    fr=await pg.inner_text('#finres')
    ok('7) 손익(원가 47%·감가상각 60개월): 손익분기 3,333만 · 비수기 보정 안내', '3,333만' in fr and '감가상각 월 167만원' in fr and '연평균 월매출 약' in fr, fr[:200])
    await pg.fill('[data-f=target]','3000'); await pg.wait_for_timeout(500)
    fr=await pg.inner_text('#finres')
    ok('8) 목표 3,000만 → 계절 막대: 적자 달 10개월 · 1년 합계 -800만', '적자 달 10개월' in fr and '-800만원' in fr)
    await pg.select_option('[data-rv=dec]','승인'); await pg.wait_for_timeout(300)
    sn=await pg.evaluate("DB.cands[0].review.snap")
    ok('9) 심사 결정 때 기준(비중·배점·손익 가정)을 같이 저장', sn and sn['weights']['comp']==20 and '심사 당시' in await pg.inner_text('#s-review'))
    await pg.evaluate("DB.weights.comp=60; save(); render()"); await pg.wait_for_timeout(300)
    rv=await pg.inner_text('#s-review')
    ok('   비중을 바꾸면 "지금 다시 계산하면 N점 — 영역 비중이 바뀜"', '지금 다시 계산하면' in rv and '영역 비중이 바뀜' in rv, rv[-160:])
    await pg.click('[data-tab=list]'); await pg.wait_for_timeout(200)
    ok('10) 백업 안 받았으면 목록 위에 경고', '아직 백업 파일을 받은 적이 없어요' in await pg.inner_text('#pane'))
    async with pg.expect_download(): await pg.click('.infobox [data-act=export]')
    await pg.wait_for_timeout(300)
    ok('   백업 받으면 경고 사라짐', '백업 파일을 받은 적이 없어요' not in await pg.inner_text('#pane'))
    # 예전 기록(비교 기준이 있던 것)을 불러와도 문제없이 열림
    old={"v":2,"stores":[],"zoneKm":2,"weights":{"hub":20,"fam":20,"biz":15,"acc":20,"comp":25,"prop":15},"benchNames":["동성로"],"bench":{"at":"2026-10-05","mode":"area","points":[]},"cands":[]}
    await pg.evaluate("o=>{ localStorage.setItem('ilpum-sk-v1',JSON.stringify(o)); }",old); await pg.reload(); await pg.wait_for_timeout(500)
    dbn=await pg.evaluate("JSON.parse(localStorage.getItem('ilpum-sk-v1')||'{}')")
    ok('11) 비교 기준이 있던 예전 기록도 열림 (비중은 새 기본으로)', await pg.evaluate("DB.weights.trade===20 && DB.weights.comp===20 && !DB.bench"), await pg.evaluate("JSON.stringify(DB.weights)"))
    ok('    오류 없음', not errs, errs)
    await b.close()
  print('모두 통과' if not FAILS else '실패 있음: '+', '.join(FAILS))
asyncio.run(main())
