# 상권분석: 장어집 기준표 점수 · 생존율 · 3km 차량 상권 · 경쟁 아님 · 손익 · 심사 기록 (t62 의 가짜 SDK·중계를 빌려 씀)
import asyncio
src=open('tests/t62.py',encoding='utf-8').read().rsplit('asyncio.run(main())',1)[0]
G={'__name__':'t62'}; exec(src,G)
from playwright.async_api import async_playwright
async def main():
  FAILS=G['FAILS']; ok=G['ok']
  async with async_playwright() as p:
    b=await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
    pg=await (await b.new_context(viewport={'width':1300,'height':900})).new_page(); errs=[]
    pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('dialog',lambda d: asyncio.ensure_future(d.accept()))
    await pg.route('**/*',G['handler']); await pg.goto('http://localhost:8765/sangkwon.html'); await pg.wait_for_timeout(600)
    ok('0) 새 기계(저장소 비어 있음)에서도 기준 만들기 없이 바로 분석', '기준 만들기' not in await pg.inner_text('#pane'))
    ok('0b) 처음 가게 형태 = 가성비 직판장형 (비중 차량25·주거20·회식10, 원가 55%·인건비 20%·객단가 3만)', await pg.evaluate("BIZ()==='outlet' && DB.weights.trade===25 && DB.weights.fam===20 && DB.weights.biz===10 && DB.fin.cost===55 && DB.fin.labor===20 && DB.fin.ticket===3"))
    await pg.click('[data-tab=set]'); await pg.check('[data-biz=std]'); await pg.wait_for_timeout(200)
    ok('0c) 일반 전문점형으로 바꾸면 비중·손익 기본값이 바뀜', await pg.evaluate("BIZ()==='std' && DB.weights.comp===20 && DB.weights.trade===20 && DB.fin.cost===47 && DB.fin.labor===25 && DB.fin.ticket===4"))
    await pg.click('[data-tab=list]'); await pg.wait_for_timeout(200)
    await pg.fill('#q','대구 수성구 범어동 177'); await pg.click('[data-act=find]'); await pg.wait_for_timeout(300)
    await pg.click('[data-cand="0"]'); await pg.wait_for_function("document.querySelector('.scorebox')",timeout=60000); await pg.wait_for_timeout(300)
    body=await pg.inner_text('#pane')
    ok('1) 장어집 기준표 점수 (비교·순위 문구 없음)', '장어집 기준표' in body and '곳 중' not in await pg.inner_text('.mix') and '기준 상권' not in body)
    ok('2) 차량 상권(3km) 영역', '차량 상권 (3km)' in body)
    sc=await pg.evaluate("(()=>{const c=DB.cands[0]; const s=scoreOf(c.m,c); const g=k=>{for(const dm of s.dims) for(const x of dm.subs) if(x.k===k) return x.p; return null}; return [g('food500'),g('park500'),g('n500'),g('eel3k'),s.mkt!=null]})()")
    ok('3) 지표 점수가 기준표(AB)대로 계산', all(v is not None for v in sc[:4]) and sc[4], sc)
    bands=await pg.evaluate("[band(12,AB.park500),band(1000,AB.subD),band(2,AB.n500),band(0,AB.eel3k),band(5,AB.eel3k),band(40,AB.eel3k)]")
    ok('4) 기준표 값: 주차 12곳 80 · 지하철 1km 55 · 장어집 2곳 60 · 3km 장어 0곳 35/5곳 90/40곳 25', bands==[80,55,60,35,90,25], bands)
    sv=await pg.evaluate("(()=>{const c=DB.cands[0]; return [c.m.eelSurv3,c.m.eelSurvN,c.m.eelDongOn,c.m.eelDongClose5]})()")
    ok('5) 장어집 3년 생존율 80% (5곳 중 4곳) · 범어동 영업 3곳', sv==[80,5,3,0], sv)
    ok('   SWOT 에 생존율 기회 문장', '3년 생존율이 80%' in body)
    cs=await pg.evaluate("(()=>{const m=DB.cands[0].m; return [m.catchN,m.pop3k,m.core3k,m.work3k,m.corp3k,m.workDong]})()")
    ok('5b) 3km 안 동 3곳: 주민 15,000·30~59세 12,000 · 직장인 12,000·사업체 1,000 · 이 동 직장인 6,000', cs==[3,15000,12000,12000,1000,6000], cs)
    ok('    개요·요약에 3km 주민·직장인 표시', '3km 안 주민' in body and '3km 안 직장인' in body)
    ok('    지표에 직장인 수·3km 30~59세, 카페·편의점·학교는 점수에서 뺌', all(x in body for x in ['직장인 수 (사업체 종사자)','30~59세 주민 수 (주 고객층)']) and '편의점 (유동 대용)' not in body)
    dens=await pg.evaluate("[band(120,AB.food500),band(600,AB.food500)]")
    ok('    음식점 수는 적당히가 최고(120곳 90점 · 600곳 40점)', dens==[90,40], dens)
    r0=await pg.evaluate("scoreOf(DB.cands[0].m,DB.cands[0]).d.n1k")
    await pg.check('[data-cx=e1]'); await pg.wait_for_timeout(300)
    r1=await pg.evaluate("scoreOf(DB.cands[0].m,DB.cands[0]).d.n1k"); ex=await pg.evaluate("DB.cands[0].compEx")
    ok('6) 경쟁 아님 체크 → 장어집 수에서 빠지고 저장', r1==r0-1 and ex=={'e1':1}, (r0,r1,ex))
    await pg.fill('[data-f=rent]','300'); await pg.fill('[data-f=area]','40'); await pg.wait_for_timeout(500)
    fr=await pg.inner_text('#finres')
    ok('7) 손익(원가 47%·감가상각 60개월): 손익분기 3,333만 · 비수기 보정 안내', '3,333만' in fr and '감가상각 월 167만원' in fr and '연평균 월매출 약' in fr, fr[:200])
    await pg.fill('[data-f=target]','3000'); await pg.wait_for_timeout(500)
    fr=await pg.inner_text('#finres')
    ok('8) 목표 3,000만 → 계절 막대: 적자 달 9개월(본점 지수) · 1년 합계 -800만', '적자 달 9개월' in fr and '-800만원' in fr)
    await pg.select_option('[data-rv=dec]','승인'); await pg.wait_for_timeout(300)
    sn=await pg.evaluate("DB.cands[0].review.snap")
    ok('9) 심사 결정 때 기준(비중·배점·손익 가정)을 같이 저장', sn and sn['weights']['comp']==20 and '심사 당시' in await pg.inner_text('#s-review'))
    await pg.evaluate("DB.weights.comp=60; save(); render()"); await pg.wait_for_timeout(300)
    rv=await pg.inner_text('#s-review')
    ok('   비중을 바꾸면 "지금 다시 계산하면 N점 — 영역 비중이 바뀜"', '지금 다시 계산하면' in rv and '영역 비중이 바뀜' in rv, rv[-160:])
    await pg.click('[data-tab=list]'); await pg.wait_for_timeout(200)
    ok('10) 백업 안 받았으면 목록 위에 경고', '아직 백업 파일을 받은 적이 없어요' in await pg.inner_text('#pane'))
    async with pg.expect_download(): await pg.click('.infobox [data-act=export]')
    await pg.wait_for_timeout(300)
    ok('   백업 받으면 경고 사라짐', '백업 파일을 받은 적이 없어요' not in await pg.inner_text('#pane'))
    # 직판장형: 경쟁점 가격대
    await pg.click('[data-tab=set]'); await pg.check('[data-biz=outlet]'); await pg.wait_for_timeout(200)
    await pg.evaluate("go('detail',DB.cands[0].id)"); await pg.wait_for_timeout(400)
    t0=await pg.evaluate("compThreat(DB.cands[0].m.comp.find(x=>x.id==='e2'),{}).t")
    await pg.select_option('[data-cq=e2][data-k=p]','1'); await pg.wait_for_timeout(200)
    t1=await pg.evaluate("compThreat(DB.cands[0].m.comp.find(x=>x.id==='e2'),DB.cands[0].compQ.e2).t")
    ok('13) 직판장형: 우리보다 비싼 장어집은 위협도 절반', abs(t1-t0*0.5)<1e-9 and await pg.evaluate("DB.cands[0].compQ.e2.p")==1, (t0,t1))
    await pg.select_option('[data-cq=e2][data-k=p]','3'); await pg.wait_for_timeout(200); await pg.evaluate("render()"); await pg.wait_for_timeout(300)
    ok('    우리보다 싼 장어집이 있으면 SWOT 위협', '우리보다 싼 장어집이 1km 안에 1곳' in await pg.inner_text('#pane'))
    ok('    주차 필수 조건이 직판장형 15대', '주차 15대 이상' in await pg.inner_text('#s-sys'))
    await pg.evaluate("DB.stores=[{name:'본점',addr:'대구 수성구 범어동 177',x:128.63,y:35.86},{name:'유천점',addr:'대구 달서구',x:128.5,y:35.8}]; save(); go('detail',DB.cands[0].id)"); await pg.wait_for_timeout(400)
    zk=await pg.evaluate("koList(DB.cands[0],scoreOf(DB.cands[0].m,DB.cands[0])).find(x=>x.t.includes('영업지역')).st")
    pane=await pg.inner_text('#pane')
    ok('14) 등록된 우리 매장 자리면 영업지역 경고 없음 + 안내 문구', zk=='ok' and '등록된 우리 매장 본점 자리예요' in pane and '영업지역이 겹쳐요' not in pane, zk)
    await pg.evaluate("DB.stores=[{name:'본점',addr:'다른 곳',x:128.64,y:35.865}]; save(); render()"); await pg.wait_for_timeout(300)
    zk=await pg.evaluate("koList(DB.cands[0],scoreOf(DB.cands[0].m,DB.cands[0])).find(x=>x.t.includes('영업지역')).st")
    ok('    다른 자리(약 1km)면 경고 그대로', zk=='fail', zk)
    ov=await pg.evaluate("[overlapPct(0),overlapPct(3000),overlapPct(6000)]")
    ok('15) 3km 상권 겹침: 같은 자리 100% · 3km 떨어지면 39% · 6km면 0%', ov==[100,39,0], ov)
    await pg.evaluate("DB.stores=[{name:'본점',addr:'다른 곳',x:128.65,y:35.86}]; save(); go('detail',DB.cands[0].id)"); await pg.wait_for_timeout(400)
    pane=await pg.inner_text('#pane'); o=await pg.evaluate("overlaps(DB.cands[0])[0].pct")
    ok('    1.8km 떨어진 본점과 겹침 표시·경고·필수 조건', o>40 and '3km 상권이 겹쳐요' in pane and '상권 겹침 40% 이하' in await pg.inner_text('#s-sys'), o)
    wt=await pg.evaluate("(()=>{ DB.takePct=50; const s=scoreOf(DB.cands[0].m,DB.cands[0]); const g=k=>s.dims.find(x=>x.k===k).w; const r=[g('hub'),g('trade')]; DB.takePct=null; return r; })()")
    ok('16) 포장 비중 50% → 외식 비중 10→5, 차량 상권 25→37.5', wt==[5,37.5], wt)
    ok('17) 앞 도로 6차선 → 4점 (현장 실사 숫자 환산)', await pg.evaluate("factVal({fx:{lanes:6}},'road')")==4)
    G['MODE']['drive']='ok'
    cs=await pg.evaluate("catchStats({x:128.63,y:35.86},'2726053000').then(o=>[o.drive,o.driveReach,o.catchN])")
    ok('18) 차로 시간 자료가 있으면 12분 넘는 점(강 건너)은 빼고 동을 셈', cs[0] is True and 8<=cs[1]<19, cs)
    G['MODE']['drive']=''
    # 예전 기록(비교 기준이 있던 것)을 불러와도 문제없이 열림
    old={"v":2,"stores":[],"zoneKm":2,"weights":{"hub":20,"fam":20,"biz":15,"acc":20,"comp":25,"prop":15},"benchNames":["동성로"],"bench":{"at":"2026-10-05","mode":"area","points":[]},"cands":[]}
    await pg.evaluate("o=>{ localStorage.setItem('ilpum-sk-v1',JSON.stringify(o)); }",old); await pg.reload(); await pg.wait_for_timeout(500)
    dbn=await pg.evaluate("JSON.parse(localStorage.getItem('ilpum-sk-v1')||'{}')")
    ok('11) 비교 기준이 있던 예전 기록도 열림 (직판장형 새 기본 비중으로)', await pg.evaluate("BIZ()==='outlet' && DB.weights.trade===25 && DB.weights.comp===15 && !DB.bench"), await pg.evaluate("JSON.stringify(DB.weights)"))
    G['MODE']['sgis']='nokey'; await pg.evaluate("Object.keys(_sgC).forEach(k=>delete _sgC[k])")
    await pg.click('[data-tab=list]'); await pg.fill('#q','대구 수성구 들안로 1'); await pg.click('[data-act=find]'); await pg.wait_for_timeout(300)
    await pg.wait_for_function("DB.cands.length&&DB.cands.at(-1).m",timeout=60000); await pg.wait_for_timeout(300)
    mm=await pg.evaluate("(()=>{const m=DB.cands.at(-1).m; return [m.work3k??null,m.pop3k,(m.pub||{}).sgis||'']})()")
    ok('12) SGIS 키 없으면 직장인 수만 빠지고 주민 수·분석은 됨', mm[0] is None and mm[1]==15000 and 'SGIS' in mm[2], mm)
    G['MODE']['sgis']=''
    ok('    오류 없음', not errs, errs)
    await b.close()
  print('모두 통과' if not FAILS else '실패 있음: '+', '.join(FAILS))
asyncio.run(main())
